Fix new -Werror compilation errors
Fix the remaining compilation errors when compiling with -Werror:

* Remove `strictfp` keywords: as of release 17, all floating-point
  expressions are evaluated strictly and 'strictfp' is not required
* java.security.AccessController in java.security has been deprecated and marked for removal
* non-varargs call of varargs method with inexact argument type for last parameter
* deprecated item is not annotated with @Deprecated
* deprecated item is not annotated with @Deprecated
* unreachable catch clause